# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algemenekosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ODE_per_kw_inclBTW', models.FloatField()),
                ('ODE_per_m3_inclBTW', models.FloatField()),
                ('energiebelasting_per_kw_inclBTW', models.FloatField()),
                ('energiebelasting_per_m3_inclBTW', models.FloatField()),
                ('BTW', models.FloatField(max_length=10)),
                ('heffingskorting_elektriciteit', models.FloatField()),
                ('jaar', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('gasprijs_per_m3', models.FloatField()),
                ('prijs_per_Kw', models.FloatField()),
                ('vastrecht_gas', models.FloatField()),
                ('vastrecht_elektriciteit', models.FloatField()),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Leveranciers',
            fields=[
                ('naam', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Netbeheerderkosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capaciteitstarief_elektriciteit_25A_onbemeten_per_jaar', models.FloatField()),
                ('capaciteitstarief_elektriciteit_25A_bemeten_per_jaar', models.FloatField()),
                ('capaciteitstarief_gas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Netbeheerders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Regiotoeslag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.CharField(max_length=4)),
                ('regio_1', models.FloatField()),
                ('regio_2', models.FloatField()),
                ('regio_3', models.FloatField()),
                ('regio_4', models.FloatField()),
                ('regio_5', models.FloatField()),
                ('regio_6', models.FloatField()),
                ('regio_7', models.FloatField()),
                ('regio_8', models.FloatField()),
                ('regio_9', models.FloatField()),
                ('regio_10', models.FloatField()),
                ('leverancier', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bereken.Leveranciers')),
            ],
        ),
        migrations.AddField(
            model_name='netbeheerderkosten',
            name='netbeheerder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bereken.Netbeheerders'),
        ),
        migrations.AddField(
            model_name='kosten',
            name='leverancier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bereken.Leveranciers'),
        ),
    ]
